#!/bin/bash
# Copyright © 2016 Martin Ueding <mu@martin-ueding.de>

set -e
set -u

dest="$HOME/archived-logs/"

for arg
do
    run="$PWD/${arg%/}"
    basename="${run##*/}"
    dirname="${run%/*}"

    echo "== $arg =="

    echo "Deleting configurations"
    pushd "$run" > /dev/null
    rm -f hmc core.*
    find . -name '*.lime' | sort | less
    echo "Is that okay?"
    read
    find . -name '*.lime' -delete
    popd > /dev/null

    pushd "$dirname" > /dev/null
    archive="$basename.tar" 
    echo "Archiving remaining files ..."
    tar -cf "$archive" "$basename"
    echo "Compressing archive ..."
    gzip -1 "$archive"
    mv "$archive.gz" "$dest"
    popd > /dev/null

    rm -rf "$run"
done
