#!/bin/bash
# Copyright © 2016 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

run="$PWD/${1%/}"
dest="$2"
basename="${run##*/}"
dirname="${run%/*}"

pushd "$run" > /dev/null
rm -f ./*.lime hmc core.*
popd > /dev/null

pushd "$dirname" > /dev/null
archive="$basename.tar.gz" 
tar -czf "$archive" "$basename"
mv "$archive" "$dest"
popd > /dev/null

rm -rf "$run"
