#!/bin/bash
# Copyright © 2016 Martin Ueding <dev@martin-ueding.de>

set -e
set -u
set -x

run="$PWD/${1%/}"
dest="$2"
basename="${run##*/}"
dirname="${run%/*}"


pushd "$run"
rm -f ./*.lime hmc core.*
popd

pushd "$dirname"
archive="$basename.tar.gz" 
tar -czf "$archive" "$basename"
mv "$archive" "$dest"
popd

rm -rf "$run"
