#!/bin/bash
# Copyright © 2017 Martin Ueding <dev@martin-ueding.de>
# Licensed under the MIT license

# Working with different batch queue management systems makes it a little
# painful. All the commands are different, the working patterns are similar.

set -e
set -u

if (( $# == 0 )); then
    cat <<EOF
Usage: $0 action

Actions:

- info
- interactive
- queue
- quota
EOF
exit 1
fi


try() {
    if type "$1" &> /dev/null; then
        "$@"
    fi
}

action=$1
shift

case "$action" in
    info)
        try sinfo -o '%11P %A'
        try qstat -Q
        ;;
    interactive)
        try salloc
        try qsub -I -A INF17_lqcd123_1
        ;;
    queue)
        try squeue -u $USER
        try qstat -u $USER
        ;;
    quota)
        try q_cpuquota
        try saldo -b --knl
        ;;
    submit)
        try sbatch "$@"
        try qsub "$@"
        ;;
esac
