#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright © 2016 Martin Ueding <martin-ueding.de>

import argparse
import subprocess


def get_job_id(output):
    '''
    >>> get_job_id('Submitted batch job 2730520')
    '2730520'
    '''
    words = output.split()
    return words[-1]


def submit_job(jobscript, dependency=None):
    command = ['sbatch']
    if dependency is not None:
        command.append('--dependency=afterok:{}'.format(dependency))
    command.append(jobscript)

    print('Running ', command)
    output = subprocess.check_output(command).decode().strip()
    print(output)

    job_id = get_job_id(output)
    print(job_id)

    return job_id


def main():
    options = _parse_args()

    job_ids = []

    for i in range(options.count):
        if len(job_ids) == 0:
            if options.depend is None:
                prev = None
            else:
                prev = options.depend
        else:
            prev = job_ids[-1]

        job_id = submit_job(options.jobscript, prev)
        job_ids.append(job_id)

    print('\nSubmitted jobs:')
    print('\n'.join(job_ids))


def _parse_args():
    '''
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    '''
    parser = argparse.ArgumentParser(description='Creates a job chain using SLURM.')
    parser.add_argument('jobscript', help='Path to the job script to run. The script must automatically start where the previous job has left. This can for instance be done using `ls -rt` to find the latest restart file.')
    parser.add_argument('count', type=int, help='Number of elements in the chain.')
    parser.add_argument('--depend', type=int, help='Use this to let the first element in the chain to be created depend on another job. Use this to extend an existing chain or to add a production chain after a single testing run.')
    options = parser.parse_args()

    return options


if __name__ == '__main__':
    main()
