#!/bin/bash
# Copyright © 2016-2018 Martin Ueding <dev@martin-ueding.de>

# Installs USQCD Chroma on with QPhiX on selected Intel-based supercomputers.
#
# This script will download the needed sources, configure, compile, and install
# them. After the script ran through, you will have a working installation of
# Chroma with QPhiX acceleration.
#
# If the machine of your interest is not support by this script, it should be
# fairly straightforward to add it. In the various `case` statements you need
# to add another block. The names of the module system will probably have to be
# adapted as well. In case you need to compile additional dependencies, it
# would sense to make this a conditional on the `$host` variable as well.

# License (MIT/Expat)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e
set -u

###############################################################################
#                                  Functions                                  #
###############################################################################

# Disables output of commands for the given command. This is useful for
# `module` commands because they are all sourced and pollute the screen.
silent() {
  set +x
  "$@"
  set -x
}

print-help() {
    cat <<EOF
Usage: $0 [OPTIONS] BASE

Have a look at the manual page (bootstrap-chroma.1.md) or its compiled version
(bootstrap.1) for a full description.
EOF
    exit 1
}

# The `module` command does not set the exit status when it fails. Also it
# annoyingly outputs everything on standard error. This function parses the
# output and checks for the word `error` case insensitively. The function will
# then fail.
checked-module() {
  module "$@" 2> module-load-output.txt
  cat module-load-output.txt
  if grep -i error module-load-output.txt; then
    set +x
    echo "There has been some error with 'module $*', aborting"
    exit 1
  fi
  rm -f module-load-output.txt
}

# Clones a git repository if the directory does not exist. It does not call
# `git pull`. After cloning, it deletes the `configure` and `Makefile` that are
# shipped by default such that they get regenerated in the next step.
clone-if-needed() {
  local url="$1"
  local dir="$2"
  local branch="$3"

  if ! [[ -d "$dir" ]]; then
      git clone "$url" --recursive -b "$branch"

      pushd "$dir"
      if [[ -f Makefile.am ]]; then
          rm -f Makefile
      fi
      rm -f configure
      popd
  fi
}

# Runs `make && make install` with appropriate flags that make compilation
# parallel on multiple cores. A sentinel file is created such that `make` is
# not invoked once it has correctly built.
make-make-install() {
  if ! [[ -f build-succeeded ]]; then
    nice make -j $_arg_make_j VERBOSE=1
    make install VERBOSE=1
    touch build-succeeded
    if [[ -d "$prefix/lib" ]]; then
      pushd "$prefix/lib"
      rm -f *.so *.so.*
      popd
    fi
  fi
}

# Prints a large heading such that it is clear where one is in the compilation
# process. This is not needed but occasionally helpful.
print-fancy-heading() {
  set +x
  echo "######################################################################"
  echo "# $*"
  echo "######################################################################"
  set -x

  if [[ -d "$sourcedir/$repo/.git" ]]; then
    pushd "$sourcedir/$repo"
    git branch
    popd
  fi
}

# Invokes the various commands that are needed to update the GNU Autotools
# build system. Since the submodules are also Autotools projects, these
# commands need to be invoked from the bottom up, recursively. The regular `git
# submodule foreach` will do a traversal from the top. Due to the nested nature
# of the GNU Autotools, we need to have depth-first traversal. Assuming that
# the directory names do not have anything funny in them, the parsing of the
# output can work.
autoreconf-if-needed() {
  if ! [[ -f configure ]]; then
    if [[ -f .gitmodules ]]; then
      for module in $(git submodule foreach --quiet --recursive pwd | tac); do
        pushd "$module"
        autoreconf -vif
        popd
      done
    fi

    aclocal
    autoreconf -vif
  fi
}

# vim: spell sts=2 sw=2
### START OF CODE GENERATED BY Argbash v2.5.1 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

die()
{
  local _ret=$2
  test -n "$_ret" || _ret=1
  test "$_PRINT_HELP" = yes && print_help >&2
  echo "$1" >&2
  exit ${_ret}
}

begins_with_short_option()
{
  local first_option all_short_options
  all_short_options='hVdmcjiqQpPsSC'
  first_option="${1:0:1}"
  test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}



# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_verbose=on
_arg_download_only=off
_arg_autodetect_machine=on
_arg_compiler=
_arg_make_j="$(nproc)"
_arg_isa=
_arg_only_qphix=off
_arg_qphix_branch="devel"
_arg_precision="double"
_arg_precision_inner="single"
_arg_soalen=
_arg_soalen_inner=
_arg_chroma_branch="devel"

print_help ()
{
  printf "%s\n" "Installs Chroma with dependencies from scratch.

This is a script to install Chroma, QPhiX, QDP++, QMP, and their
dependencies on the following HPC systems:

+--------------+----------------------------+------------------------------+
| Name         | Architecture               | Location                     |
+==============+============================+==============================+
| Hazel Hen    | Haswell (AVX2)             | Stuttgart, Germany           |
+--------------+----------------------------+------------------------------+
| JURECA       | Haswell (AVX2)             | Jülich, Germany              |
+--------------+----------------------------+------------------------------+
| Marconi A2   | Knights Landing (AVX512)   | Casalecchio di Reno, Italy   |
+--------------+----------------------------+------------------------------+

The script will automatically find out which computer you run it on. If
this check fails, the script need to be fixed.

After this script ran though, you will have the following directories::

    BASE/build-icc/chroma
    BASE/build-icc/libxml2
    BASE/build-icc/qdpxx
    BASE/build-icc/qmp
    BASE/build-icc/qphix

    BASE/local-icc/bin
    BASE/local-icc/include
    BASE/local-icc/lib
    BASE/local-icc/share

    BASE/sources/chroma
    BASE/sources/libxml2
    BASE/sources/qdpxx
    BASE/sources/qmp
    BASE/sources/qphix
"
  printf 'Usage: %s [-h|--help] [-V|--(no-)verbose] [-d|--(no-)download-only] [-m|--(no-)autodetect-machine] [-c|--compiler <arg>] [-j|--make-j <arg>] [-i|--isa <arg>] [-q|--(no-)only-qphix] [-Q|--qphix-branch <arg>] [-p|--precision <arg>] [-P|--precision-inner <arg>] [-s|--soalen <arg>] [-S|--soalen-inner <arg>] [-C|--chroma-branch <arg>] <basedir>\n' "$0"
  printf "\t%s\n" "<basedir>: Base path"
  printf "\t%s\n" "-h,--help: Prints help"
  printf "\t%s\n" "-V,--verbose,--no-verbose: Print Bash commands executed (on by default)"
  printf "\t%s\n" "-d,--download-only,--no-download-only: Download only (for systems like Hazel Hen) (off by default)"
  printf "\t%s\n" "-m,--autodetect-machine,--no-autodetect-machine: Automatically figure out which machine we are on (on by default)"
  printf "\t%s\n" "-c,--compiler: Compiler family to use, defaults to best on given machine (no default)"
  printf "\t%s\n" "-j,--make-j: Maximum number of parallel processes used by make (default: '"$(nproc)"')"
  printf "\t%s\n" "-i,--isa: Manual instruction set architecture (ISA), usually automatically set (no default)"
  printf "\t%s\n" "-q,--only-qphix,--no-only-qphix: Only compile QPhiX, not Chroma (off by default)"
  printf "\t%s\n" "-Q,--qphix-branch: QPhiX git branch (default: '"devel"')"
  printf "\t%s\n" "-p,--precision: Precision of solver, can be "double", "float" (default: '"double"')"
  printf "\t%s\n" "-P,--precision-inner: Precision of inner solver, can be "double", "float" or "half" (default: '"single"')"
  printf "\t%s\n" "-s,--soalen: Structure of array (SoA) length (no default)"
  printf "\t%s\n" "-S,--soalen-inner: Structure of array (SoA) length for inner solver (no default)"
  printf "\t%s\n" "-C,--chroma-branch: Chroma git branch (default: '"devel"')"
}

parse_commandline ()
{
  while test $# -gt 0
  do
    _key="$1"
    case "$_key" in
      -h|--help)
        print_help
        exit 0
        ;;
      -h*)
        print_help
        exit 0
        ;;
      -V|--no-verbose|--verbose)
        _arg_verbose="on"
        test "${1:0:5}" = "--no-" && _arg_verbose="off"
        ;;
      -V*)
        _arg_verbose="on"
        _next="${_key##-V}"
        if test -n "$_next" -a "$_next" != "$_key"
        then
          begins_with_short_option "$_next" && shift && set -- "-V" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
        fi
        ;;
      -d|--no-download-only|--download-only)
        _arg_download_only="on"
        test "${1:0:5}" = "--no-" && _arg_download_only="off"
        ;;
      -d*)
        _arg_download_only="on"
        _next="${_key##-d}"
        if test -n "$_next" -a "$_next" != "$_key"
        then
          begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
        fi
        ;;
      -m|--no-autodetect-machine|--autodetect-machine)
        _arg_autodetect_machine="on"
        test "${1:0:5}" = "--no-" && _arg_autodetect_machine="off"
        ;;
      -m*)
        _arg_autodetect_machine="on"
        _next="${_key##-m}"
        if test -n "$_next" -a "$_next" != "$_key"
        then
          begins_with_short_option "$_next" && shift && set -- "-m" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
        fi
        ;;
      -c|--compiler)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_compiler="$2"
        shift
        ;;
      --compiler=*)
        _arg_compiler="${_key##--compiler=}"
        ;;
      -c*)
        _arg_compiler="${_key##-c}"
        ;;
      -j|--make-j)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_make_j="$2"
        shift
        ;;
      --make-j=*)
        _arg_make_j="${_key##--make-j=}"
        ;;
      -j*)
        _arg_make_j="${_key##-j}"
        ;;
      -i|--isa)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_isa="$2"
        shift
        ;;
      --isa=*)
        _arg_isa="${_key##--isa=}"
        ;;
      -i*)
        _arg_isa="${_key##-i}"
        ;;
      -q|--no-only-qphix|--only-qphix)
        _arg_only_qphix="on"
        test "${1:0:5}" = "--no-" && _arg_only_qphix="off"
        ;;
      -q*)
        _arg_only_qphix="on"
        _next="${_key##-q}"
        if test -n "$_next" -a "$_next" != "$_key"
        then
          begins_with_short_option "$_next" && shift && set -- "-q" "-${_next}" "$@" || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
        fi
        ;;
      -Q|--qphix-branch)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_qphix_branch="$2"
        shift
        ;;
      --qphix-branch=*)
        _arg_qphix_branch="${_key##--qphix-branch=}"
        ;;
      -Q*)
        _arg_qphix_branch="${_key##-Q}"
        ;;
      -p|--precision)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_precision="$2"
        shift
        ;;
      --precision=*)
        _arg_precision="${_key##--precision=}"
        ;;
      -p*)
        _arg_precision="${_key##-p}"
        ;;
      -P|--precision-inner)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_precision_inner="$2"
        shift
        ;;
      --precision-inner=*)
        _arg_precision_inner="${_key##--precision-inner=}"
        ;;
      -P*)
        _arg_precision_inner="${_key##-P}"
        ;;
      -s|--soalen)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_soalen="$2"
        shift
        ;;
      --soalen=*)
        _arg_soalen="${_key##--soalen=}"
        ;;
      -s*)
        _arg_soalen="${_key##-s}"
        ;;
      -S|--soalen-inner)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_soalen_inner="$2"
        shift
        ;;
      --soalen-inner=*)
        _arg_soalen_inner="${_key##--soalen-inner=}"
        ;;
      -S*)
        _arg_soalen_inner="${_key##-S}"
        ;;
      -C|--chroma-branch)
        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
        _arg_chroma_branch="$2"
        shift
        ;;
      --chroma-branch=*)
        _arg_chroma_branch="${_key##--chroma-branch=}"
        ;;
      -C*)
        _arg_chroma_branch="${_key##-C}"
        ;;
      *)
        _positionals+=("$1")
        ;;
    esac
    shift
  done
}


handle_passed_args_count ()
{
  _required_args_string="'basedir'"
  test ${#_positionals[@]} -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${#_positionals[@]}." 1
  test ${#_positionals[@]} -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${#_positionals[@]} (the last one was: '${_positionals[*]: -1}')." 1
}

assign_positional_args ()
{
  _positional_names=('_arg_basedir' )

  for (( ii = 0; ii < ${#_positionals[@]}; ii++))
  do
    eval "${_positional_names[ii]}=\${_positionals[ii]}" || die "Error during argument parsing, possibly an Argbash bug." 1
  done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash
# ] <-- needed because of Argbash

###############################################################################
#                              Environment Setup                              #
###############################################################################

# With `set -x`, Bash will output all commands that are run. This changes the
# output such that the number of seconds is printed out with each line. This
# will give some feeling for the time it needs to compile.
PS4='+[${SECONDS}s] '

if [[ "$_arg_verbose" = on ]]; then
  set -x
fi

# Create the target directory and then store the absolute path to this
# directory. Many compilation scripts have issues with linking to relative
# paths.
mkdir -p "$_arg_basedir"
pushd "$_arg_basedir"
basedir="$PWD"
popd

# Directory where the git repositories reside.
sourcedir="$basedir/sources"
mkdir -p "$sourcedir"

# Set all locale to C, such that compiler error messages are all in English.
# This makes debugging way easier because you can search for the messages
# online.
export LC_ALL=C

###############################################################################
#                                  Download                                   #
###############################################################################

# Download is done as an early step. This allows users to download all the
# needed files on a different machine as internet access is blocked on machines
# like Hazel Hen.

pushd "$sourcedir"

# CMake
repo=cmake
url=https://cmake.org/files/v3.9/cmake-3.9.1.tar.gz
if ! [[ -f "${url##*/}" ]]; then
  wget "$url"
fi
if ! [[ -d "$repo" ]]; then
  tar -xf "${url##*/}"
  mv cmake-3.9.1 cmake
fi

# QMP
repo=qmp
clone-if-needed https://github.com/usqcd-software/qmp.git $repo master

# libxml2
repo=libxml2
clone-if-needed https://git.gnome.org/browse/libxml2 $repo v2.9.4

# QDP++
repo=qdpxx
clone-if-needed https://github.com/usqcd-software/qdpxx.git $repo devel

# QPhiX
repo=qphix
clone-if-needed https://github.com/JeffersonLab/qphix.git $repo "$_arg_qphix_branch"

# GNU MP
repo=gmp
if ! [[ -d "$repo" ]];
then
  # The upstream website only has a download as an LZMA compressed file. The
  # CentOS does not provide an `lzip` command. Also, there is no module
  # available that would supply it. Building `lzip` from source seems like a
  # waste of effort. Therefore I have just repacked that on my local machine
  # and uploaded to my webspace.
  url=http://bulk.martin-ueding.de/gmp-6.1.2.tar.gz
  #url=https://gmplib.org/download/gmp/gmp-6.1.2.tar.lz

  wget "$url"
  tar -xf "${url##*/}"
  mv gmp-6.1.2 gmp
fi

# Chroma
repo=chroma
clone-if-needed https://github.com/JeffersonLab/chroma.git $repo "$_arg_chroma_branch"

if [[ "$_arg_download_only" = on ]]; then
  set +x
  echo "User wanted do download only, we are done here."
  exit 0
fi

popd

###############################################################################
#                           Compiler Flag Selection                           #
###############################################################################

# Determine the fully qualified hostname and then set the optimal default
# compiler for the architecture found.
hostname_f="$(hostname -f)"

if [[ "$_arg_autodetect_machine" = off ]]; then
  if [[ -z "$_arg_isa" ]]; then
    echo "Builds on local machines require the -i option to be passed (ISA: avx, avx2, avx512)"
    exit 1
  fi
  host=local
  isa=$_arg_isa
  compiler="${_arg_compiler:-gcc}"
else
  if [[ "$hostname_f" =~ eslogin[0-9]+ ]]; then
    host=hazelhen
    isa=avx2
    compiler="${_arg_compiler:-icc}"
  elif [[ "$hostname_f" =~ [^.]*\.jureca ]]; then
    host=jureca
    isa=avx2
    compiler="${_arg_compiler:-icc}"
  elif [[ "$hostname_f" =~ [^.]*\.marconi.cineca.it ]]; then
    if [[ -n "${ENV_KNL_HOME-}" ]]; then
      host=marconi-a2
      isa=avx512
      compiler="${_arg_compiler:-icc}"
    else
      set +x
      echo 'You seem to be running on Marconi but the environment variable ENV_KNL_HOME is not set. This script currently only supports Marconi A2, so please do `module load env-knl` to select the KNL partition.'
      exit 1
    fi
  else
    set +x
    echo "This machine is neither explicitly a 'local' machine nor JURECA nor Hazel Hen nor Marconi A2. It is not clear what should be done, please update the script."
    exit 1
  fi
fi

# Set up the chosen compiler.
case "$compiler" in
  # The cray compiler does not support half-precision data types (yet). So
  # one cannot actually use that for QPhiX right now.
  cray)
    cc_name=cc
    cxx_name=CC
    color_flags=""
    openmp_flags=""
    base_flags="-O2 -hcpu=haswell"
    c99_flags="-hstd=c99"
    cxx11_flags="-hstd=c++11"
    disable_warnings_flags=""
    qphix_flags=""
    qphix_configure=""
    ;;
  icc)
    color_flags=""
    openmp_flags="-fopenmp"
    c99_flags="-std=c99"
    cxx11_flags="-std=c++11"
    disable_warnings_flags="-Wno-all -Wno-pedantic -diag-disable 1224"
    qphix_flags="-restrict"
    # QPhiX can make use of the Intel “C Extended Array Notation”, this
    # gets enabled here.
    qphix_configure="--enable-cean"

    case "$host" in
      jureca)
        checked-module load Intel/2017.2.174-GCC-5.4.0
        checked-module load IntelMPI/2017.2.174
        silent module list
        cc_name=mpiicc
        cxx_name=mpiicpc
        host_cxx=icpc
        base_flags="-xAVX2 -O3"
        ;;
      hazelhen)
        # On Hazel Hen, the default compiler is the Cray compiler. One needs to
        # unload that and load the Intel programming environment. That should
        # also load the Intel MPI implementation.
        checked-module swap PrgEnv-cray PrgEnv-intel
        # If one does not load a newer GCC version, the modern Intel compiler
        # will use the GCC 4.3 standard library. That however does not support
        # C++11 such that it will not work.
        checked-module load gcc/6.3.0
        checked-module load intel/17.0.2.174
        silent module list
        # On this system, the compiler is always the same because the module
        # system loads the right one of these wrappers.
        cc_name=cc
        cxx_name=CC
        host_cxx=icpc
        base_flags="-xAVX2 -O3"
        ;;
      marconi-a2)
        checked-module load intel/pe-xe-2017--binary
        checked-module load intelmpi
        silent module list
        cc_name=mpiicc
        cxx_name=mpiicpc
        host_cxx=icpc
        base_flags="-xMIC-AVX512 -O3"
        ;;
    esac
    ;;
  gcc)
    color_flags="-fdiagnostics-color=auto"
    openmp_flags="-fopenmp"
    c99_flags="--std=c99"
    cxx11_flags="--std=c++11"
    disable_warnings_flags="-Wno-all -Wno-pedantic"
    qphix_flags="-Drestrict=__restrict__"
    qphix_configure=""

    case "$host" in
      jureca)
        checked-module load GCC
        checked-module load ParaStationMPI
        silent module list
        cc_name=mpicc
        cxx_name=mpic++
        host_cxx=g++
        base_flags="-O3 -finline-limit=50000 $color_flags -march=haswell"
        ;;
      hazelhen)
        silent module swap PrgEnv-cray PrgEnv-gnu
        silent module list
        cc_name=cc
        cxx_name=CC
        host_cxx=g++
        base_flags="-O3 -finline-limit=50000 $color_flags -march=haswell"
        ;;
      marconi-a2)
        checked-module load gnu
        checked-module load ParaStationMPI
        silent module list
        cc_name=mpicc
        cxx_name=mpic++
        host_cxx=g++
        base_flags="-O3 -finline-limit=50000 -fmax-errors=1 $color_flags -march=knl"
        ;;
      local)
        cc_name=mpicc
        cxx_name=mpic++
        host_cxx=g++
        base_flags="-O3 -finline-limit=50000 -fmax-errors=1 $color_flags -march=native"
        ;;
    esac
    ;;
  *)
    echo 'This compiler is not supported by this script. Choose another one or add another block to the `case` in this script.'
    exit 1
    ;;
esac

# Directory for the installed files (headers, libraries, executables). This
# contains the chosen compiler in the dirname such that multiple compilers can
# be used simultaneously.
prefix="$basedir/local-$compiler"
mkdir -p "$prefix"

# Directory for building. The GNU Autotools support out-of-tree builds which
# allow to use different compilers on the same codebase.
build="$basedir/build-$compiler"
mkdir -p "$build"

# The GNU Autotools install `X-config` programs that let a dependent library
# query the `CFLAGS` and `CXXFLAGS` used in the compilation. This needs to be
# in the `$PATH`, otherwise libraries cannot be found properly. In principle it
# should be sufficient to pass the installation path to the `configure` scripts
# but this has not always worked properly, therefore this additional thing.
# Additionally we might install auxiliary software like CMake on some systems,
# we want it to be preferred over the system-wide installed versions.
PATH=$prefix/bin:$PATH

# Basic flags that will be used for all compilations. The full path to the C
# and C++ compiler are queried here and stored. Changes in modules later on
# will not alter the compilers, therefore.
base_cxxflags="$base_flags"
base_cflags="$base_flags $c99_flags"
base_configure="--prefix=$prefix CC=$(which $cc_name) CXX=$(which $cxx_name) --enable-option-checking"

case "$host" in
  hazelhen)
    # The “huge pages” are used on Hazel Hen. This leads to the inability to run
    # execute programs on the login nodes that are compiled with the MPI compiler
    # wrapper. Autotools need to be told that it cross compiles such that the
    # `./configure` script won't try to execute the test programs.
    base_configure="$base_configure --host=x86_64-linux-gnu"
    ;;
  marconi-a2)
    # Marconi A2 has a cross compilation from Haswell to Knights Landing,
    # therefore one needs to tell GNU Autotools that programs compiled with the
    # target compiler cannot be executed on the host.
    base_configure="$base_configure --host=x86_64-linux-gnu"
    ;;
esac

cd "$sourcedir"

###############################################################################
#                                    CMake                                    #
###############################################################################

# Hazel Hen only has version 2.6 of CMake which is too old for us. There is a
# newer version, but that can only be used when the GNU compiler is loaded. It
# does not work with the Intel compiler. Trying to find the path of the modern
# version of CMake works, but then it cannot load the GNU standard library,
# *sigh*.
#
# I have contacted the support on 2017-08-21 and they will provide a more
# modern version of CMake that can be used with the Intel compiler. For the
# meantime, we install CMake ourselves here and use that.

#repo=cmake
#print-fancy-heading $repo
#
#case "$host" in
#  hazelhen)
#    pushd "$repo"
#    if ! [[ -f Makefile ]]; then
#      ./bootstrap --prefix="$prefix"
#    fi
#    make-make-install
#    popd
#    ;;
#esac

###############################################################################
#                                     QMP                                     #
###############################################################################

repo=qmp
print-fancy-heading $repo

cflags="$base_cflags $openmp_flags"
cxxflags="$base_cxxflags $openmp_flags"

pushd $repo
autoreconf-if-needed
popd

mkdir -p "$build/$repo"
pushd "$build/$repo"
if ! [[ -f Makefile ]]; then
  $sourcedir/$repo/configure $base_configure \
    --with-qmp-comms-type=MPI \
    CFLAGS="$cflags" CXXFLAGS="$cxxflags"
fi
make-make-install
popd

###############################################################################
#                                   libxml2                                   #
###############################################################################

repo=libxml2
print-fancy-heading $repo

case "$host" in
  jureca|marconi-a2)
    cflags="$base_cflags"
    cxxflags="$base_cxxflags"

    pushd $repo
    if ! [[ -f configure ]]; then
      mkdir -p m4
      pushd m4
      ln -fs /usr/share/aclocal/pkg.m4 .
      popd
      checked-module load Autotools
      NOCONFIGURE=yes ./autogen.sh
    fi
    popd

    mkdir -p "$build/$repo"
    pushd "$build/$repo"
    if ! [[ -f Makefile ]]; then
      $sourcedir/$repo/configure $base_configure \
        --without-zlib \
        --without-python \
        --without-readline \
        --without-threads \
        --without-history \
        --without-reader \
        --without-writer \
        --with-output \
        --without-ftp \
        --without-http \
        --without-pattern \
        --without-catalog \
        --without-docbook \
        --without-iconv \
        --without-schemas \
        --without-schematron \
        --without-modules \
        --without-xptr \
        --without-xinclude \
        CFLAGS="$cflags" CXXFLAGS="$cxxflags"
    fi
    make-make-install
    popd

    libxml="$prefix/bin/xml2-config"
    ;;
  hazelhen)
    cflags="$base_cflags"
    cxxflags="$base_cxxflags"

    pushd $repo
    if ! [[ -f configure ]]; then
      mkdir -p m4
      pushd m4
      ln -fs /usr/share/aclocal/pkg.m4 .
      popd
      NOCONFIGURE=yes ./autogen.sh
    fi
    popd

    mkdir -p "$build/$repo"
    pushd "$build/$repo"
    if ! [[ -f Makefile ]]; then
      $sourcedir/$repo/configure $base_configure \
        --without-zlib \
        --without-python \
        --without-readline \
        --without-threads \
        --without-history \
        --without-reader \
        --without-writer \
        --with-output \
        --without-ftp \
        --without-http \
        --without-pattern \
        --without-catalog \
        --without-docbook \
        --without-iconv \
        --without-schemas \
        --without-schematron \
        --without-modules \
        --without-xptr \
        --without-xinclude \
        CFLAGS="$cflags" CXXFLAGS="$cxxflags"
    fi
    make-make-install
    popd

    libxml="$prefix/bin/xml2-config"
    ;;
  local)
    libxml="/usr/include/libxml2"
    ;;
esac

###############################################################################
#                                    QDP++                                    #
###############################################################################

repo=qdpxx
print-fancy-heading $repo

cflags="$base_cflags $openmp_flags"
cxxflags="$base_cxxflags $openmp_flags $cxx11_flags"

pushd $repo
autoreconf-if-needed
popd

mkdir -p "$build/$repo"
pushd "$build/$repo"
if ! [[ -f Makefile ]]; then
  $sourcedir/$repo/configure $base_configure \
    --enable-openmp \
    --enable-sse --enable-sse2 \
    --enable-parallel-arch=parscalar \
    --enable-parallel-io \
    --enable-precision=$_arg_precision \
    --with-libxml2="$libxml" \
    --with-qmp="$prefix" \
    CFLAGS="$cflags" CXXFLAGS="$cxxflags"
fi
make-make-install
popd

###############################################################################
#                                    QPhiX                                    #
###############################################################################

repo=qphix
print-fancy-heading $repo

case $host in
  jureca)
    checked-module load CMake
    checked-module load Python
    ;;
  hazelhen)
    checked-module load tools/python

    python_library=/opt/hlrs/tools/python/anaconda3-4.2.0/lib/libpython3.so
    python_include_dir=/opt/hlrs/tools/python/anaconda3-4.2.0/include
    ;;
  marconi-a2)
    checked-module load cmake
    checked-module load python
    ;;
esac

set +x
if [[ "$host" != "local" ]]; then
  module list
fi
set -x

# Check whether Python 3 interpreter is there. The following calls Python 3 and
# lets it do explicitly nothing. That must always work. Then we output the path
# for reference.
python3 -c ''
which python3

cxxflags="$base_cxxflags $openmp_flags $cxx11_flags $qphix_flags"
cxx=$(which $cxx_name)

# Due to the module system, the `python3` executable can be found in the
# `$PATH`, but somehow CMake cannot find what it needs. Therefore we need to
# set those paths manually. Fortunately we can [use Python to give this to
# us](https://stackoverflow.com/a/38121972) and pass that on to CMake.
cmake_python_include_dir="$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")"
cmake_python_library="$(python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")"

mkdir -p "$build/$repo"
pushd "$build/$repo"
if ! [[ -f Makefile ]]; then
  cxx=$(which $cxx_name)
  CXX=$cxx CXXFLAGS="$cxxflags" \
    cmake -Disa=$isa \
    -Dhost_cxx="$host_cxx" \
    -Dhost_cxxflags="$cxx11_flags" \
    -Drecursive_jN=$(nproc) \
    -DCMAKE_INSTALL_PREFIX="$prefix" \
    -DQDPXX_DIR="$prefix" \
    -Dclover=TRUE \
    -Dtwisted_mass=TRUE \
    -Dtm_clover=TRUE \
    -Dcean=FALSE \
    -Dmm_malloc=TRUE \
    -Dtesting=TRUE \
    -DPYTHON_INCLUDE_DIR="$cmake_python_include_dir"  \
    -DPYTHON_LIBRARY="$cmake_python_library" \
    $sourcedir/$repo
fi
make-make-install
popd

if [[ "$_arg_only_qphix" = "true" ]]; then
  echo "QPhiX is installed, user wished to abort here."
  exit 0
fi

case $host in
  hazelhen)
    # Now we have to get our target programming environment back.
    module swap PrgEnv-gnu PrgEnv-intel
    checked-module load gcc/6.3.0
    checked-module load intel/17.0.2.174
    ;;
esac

###############################################################################
#                             GNU Multi Precision                             #
###############################################################################

repo=gmp
print-fancy-heading $repo

case "$host" in
  jureca)
    set +x
    checked-module load GMP
    set -x
    gmp="$EBROOTGMP"
    ;;
  hazelhen)
    gmp="-lgmp"
    ;;
  marconi-a2)
    # The GNU MP library installed on the Marconi system, but it might be
    # linked against an older version of the standard library. Therefore we
    # compile it from scratch.

    repo=gmp
    print-fancy-heading $repo

    cflags="$base_cflags"
    cxxflags="$base_cxxflags"

    pushd "$repo"
    autoreconf-if-needed
    popd

    mkdir -p "$build/$repo"
    pushd "$build/$repo"
    if ! [[ -f Makefile ]]; then
      $sourcedir/$repo/configure $base_configure \
        CFLAGS="$cflags" CXXFLAGS="$cxxflags"
    fi
    make-make-install
    popd

    gmp="$prefix"
    ;;
esac

###############################################################################
#                                   Chroma                                    #
###############################################################################

repo=chroma
print-fancy-heading $repo

cflags="$base_cflags $openmp_flags"
cxxflags="$base_cxxflags $openmp_flags"

pushd $repo
autoreconf-if-needed
popd

# Select a default SoA length.
case "$host" in
  jureca|hazelhen)
    soalen=4
    inner_soalen=4
    ;;
  marconi-a2)
    soalen=8
    inner_soalen=4
    ;;
esac

# Overwrite with the value that the user has chosen, if it is set.
soalen=${_arg_soalen-$soalen}
inner_soalen=${_arg_soalen_inner-$inner_soalen}

mkdir -p "$build/$repo"
pushd "$build/$repo"
if ! [[ -f Makefile ]]; then
  $sourcedir/$repo/configure $base_configure \
    --enable-openmp \
    --enable-parallel-arch=parscalar \
    --enable-parallel-io \
    --enable-precision=$_arg_precision \
    --enable-qdp-alignment=128 \
    --enable-sse2 \
    --with-gmp="$gmp" \
    --with-libxml2="$libxml" \
    --with-qdp="$prefix" \
    --with-qphix-solver="$prefix" \
    --enable-qphix-solver-compress12 \
    --enable-qphix-solver-arch=$isa \
    --enable-qphix-solver-soalen=$soalen \
    --enable-qphix-solver-inner-soalen=$inner_soalen \
    --enable-qphix-solver-inner-type=$_arg_precision_inner \
    CFLAGS="$cflags" CXXFLAGS="$cxxflags"
fi
make-make-install
popd

echo
echo "That took $SECONDS seconds."

# vim: spell sts=2 sw=2
