#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2017 Martin Ueding <dev@martin-ueding.de>
# Licensed under the MIT/Expat license.

import argparse
import os
import shutil
import sys

import jinja2


def main():
    options = _parse_args()

    # Run the consistency checks before doing anything. After all checks are
    # through, we may do things that change files on disk.
    do_consistency_checks(options)

    # Load the templates from the directory that this script is located in.
    # This path can be queried from the zeroth command line argument.
    env = jinja2.Environment(loader=jinja2.FileSystemLoader(
        os.path.dirname(os.path.abspath(sys.argv[0]))))

    template_contract = env.get_template('contract.in.j2')
    template_pbs = env.get_template('job_script.pbs.j2')

    # Load the list with correlators.
    with open(options.correlator_list) as f:
        correlator_list = f.read()

    # Create the main work directory.
    os.makedirs(options.rundir, exist_ok=True)

    # Copy the executable into the right spot.
    shutil.copy(options.exe, os.path.join(options.rundir, 'contract'))

    # Create a list with all configuration numbers. Configurations that should
    # be skipped will be filtered out.
    config_ids = filter(
        lambda x: x not in options.conf_skip,
        (range(options.conf_start, options.conf_end + 1, options.conf_step)))

    for config_id in config_ids:
        # Create a directory for the configuration.
        config_path = os.path.join(options.rundir, 'cnfg{:04d}'.format(config_id))
        os.makedirs(config_path, exist_ok=True)

        # Create an input file for the contraction code.
        rendered_contract = template_contract.render(
            lattice_time=options.lattice_time,
            lattice_space=options.lattice_space,
            config_start=config_id,
            config_end=config_id,
            config_step=1,
            ev_count=options.ev_count,
            ev_path=options.ev_path,
            quarks=options.quarks,
            correlator_list=correlator_list,
        )
        with open(os.path.join(config_path, 'contract.in'), 'w') as f:
            f.write(rendered_contract)

        # Create a job script for the scheduler.
        rendered_pbs = template_pbs.render(
            email_address=options.email,
            rundir=config_path,
        )
        with open(os.path.join(config_path, 'job_script.pbs'), 'w') as f:
            f.write(rendered_contract)


def do_consistency_checks(options):
    '''
    This runs various consistency checks.

    If something is off, an exception is raised with an explanation.
    '''
    # Skip the tests in case the user wants to ignore them.
    if options.ignore_checks:
        return

    # Check that the executable exists.
    if not os.path.isfile(options.exe):
        raise RuntimeError('The executable at “{}” does not exist! Please make sure that a correct path has been given.'.format(options.exe))

    if not os.path.isfile(options.correlator_list):
        raise RuntimeError('The file with the correlators at “{}” does not exist! Please make sure that a correct path has been given.'.format(options.correlator_list))

    for quark in options.quarks:
        segments = quark.split(':')
        path = segments[-1]
        if not os.path.isdir(path):
            raise RuntimeError('The quark path “{}” does not exist! Please make sure that a correct path has been given.'.format(options.correlator_list))


def _parse_args():
    parser = argparse.ArgumentParser(description='Generates a hierarchy of input files and job scripts for the contraction code. The script will also make sure that the referenced files actually exist such that the jobs will have a higher chance of succeeding.')

    parser.add_argument('--ignore-checks', action='store_true', help='Do not run the tests for existence of input files.')

    group_config = parser.add_argument_group('Configuration', 'Options that are inherent for the underlying gauge configurations.')
    group_config.add_argument('conf_start', type=int, help='First configuration, inclusive')
    group_config.add_argument('conf_end', type=int, help='Last configuration, inclusive')
    group_config.add_argument('conf_step', type=int, nargs='?', default=8, help='default: %(default)s')
    group_config.add_argument('--lattice-space', type=int, required=True, help='Size of the lattice in the space directions. Currently only lattices with equal space extents are supported.')
    group_config.add_argument('--lattice-time', type=int, required=True, help='Size of the lattice in time direction.')
    group_config.add_argument('--conf-skip', type=int, nargs='+', help='Skip the given gauge configurations.')

    group_job = parser.add_argument_group('Job', 'Options for the jobs to create.')
    group_job.add_argument('--rundir', required=True, help='Base path for output.')
    group_job.add_argument('--exe', required=True, help='Path to the executable. This will be copied into the hierarchy to prevent accidential overwrites.')
    group_job.add_argument('--jobname', default='contraction', help='Name of the PBS job. Default: %(default)s')
    group_job.add_argument('--email', default='', help='Email address to send job notifications to. If this is not given, no emails will be send.')

    group_ev = parser.add_argument_group('Eigenvector', 'Information about the eigenvectors.')
    group_ev.add_argument('--ev-count', type=int, required=True, help='Number of eigenvectors')
    group_ev.add_argument('--ev-path', default='', help='Path to eigenvectors. These are only required when looking at moving frames.')

    group_contraction = parser.add_argument_group('Contraction', 'Options for the contractions themselves.')
    group_contraction.add_argument('--quark', nargs='+', required=True, dest='quarks', metavar='QUARK', help='Quark line including the path. Example: u:6:TF:1:EI:6:DF:4:/hiskp2/bartek/peram_generation/0120-Mpi270-L24-T96/light.ranlxd2.apbc_no_compression')
    group_contraction.add_argument('--correlator-list', required=True, help='Path to text file which contains the correlator definitions')

    options = parser.parse_args()
    return options


if __name__ == "__main__":
    main()
