#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright © 2016 Martin Ueding <dev@martin-ueding.de>

import argparse
import os
import subprocess

import jinja2


def main():
    options = _parse_args()

    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(".")
    )
    template = env.get_template('chroma-smear.template.xml')

    for gauge_config in options.gauge_config:
        print('Working on {} …'.format(gauge_config))
        base, ext = os.path.splitext(gauge_config)

        filename_smeared = '{}.stout6{}'.format(base, ext)
        filename_xml = '{}.stout6.xml'.format(base)
        filename_chroma_input = '{}-smear.chroma-ini.xml'.format(base)

        rendered = template.render(
            config_in_file=gauge_config,
            config_out_file=filename_smeared,
            xml_out_file=filename_xml,
        )

        with open(filename_chroma_input, 'w') as f:
            f.write(rendered)



def _parse_args():
    '''
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    '''
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('gauge_config', nargs='+', help='LIME files to smear')
    options = parser.parse_args()

    return options


if __name__ == '__main__':
    main()
